site_name: Test Doc Webpage
pages:
  - Home: index.md
#  - About: markdown.md
  - Access API: api.md
  - API endpoints:
    - user: api-userinfo.md
    - docs: api-getnote.md
  - Tabs: tabs.md
theme: material
extra_css:
  - css/code-tabs.css
extra_javascript:
  - js/code-tabs.js
markdown_extensions:
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
